/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import soot.PackManager;
import soot.options.Options;

import java.io.IOException;

public class App {

    public static void main(String[] args) throws DootException, IOException, InterruptedException {
        Parameters parameters = new Parameters();
        parameters.initFromArgs(args);

        Driver driver = new Driver(parameters._example, parameters._mainClass, parameters._doopDir);
        driver.setupSoot();

        if (!parameters._skipDoop) {
            driver.invokeDoop();
        }

        if (!parameters._skipOptimize) {
            driver.optimize();
        }

        switch (parameters._outputFormat) {
            case "shimple":
                Options.v().set_output_format(Options.output_format_shimple);
                break;
            case "class":
                driver.transformAllToJimpleBodies();
                Options.v().set_output_format(Options.output_format_class);
                break;
            default:
                throw new DootException("Unsupported output format: " + parameters._outputFormat);
        }
        PackManager.v().writeOutput();
    }
}
