/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import soot.PackManager;
import soot.options.Options;

public class App {

    public static void main(String[] args) throws DootException {
        Parameters parameters = new Parameters();
        parameters.initFromArgs(args);

        Driver driver = new Driver(parameters._example, parameters._mainClass);
        driver.setupSoot();

        driver.invokeDoop();

        String cls = "Naive";
        String method = "void main(java.lang.String[])";
        String assignee = "l3#_10";
        String assignor = "Hello, World!";
        Driver.ValueType assignorType = Driver.ValueType.STRING;
        driver.optimizeInverseVariables(cls, method, assignee, assignor, assignorType);

        switch (parameters._outputFormat) {
            case "shimple":
                Options.v().set_output_format(Options.output_format_shimple);
                break;
            case "class":
                driver.transformAllToJimpleBodies();
                Options.v().set_output_format(Options.output_format_class);
                break;
            default:
                throw new DootException("Unsupported output format: " + parameters._outputFormat);
        }
        PackManager.v().writeOutput();
    }
}
