./gradlew run --args="-e optimizeString -o class --doop-dir /home/xinsu/Desktop/Thesis/doop --optimize --keep-tmp-dir"
#./gradlew run --args="-e optimizeVar -o class --doop-dir /home/xinsu/Desktop/Thesis/doop --optimize --keep-tmp-dir"
#./gradlew run --args="-e optimizeNotConsecutive -o class --doop-dir /home/xinsu/Desktop/Thesis/doop --optimize --keep-tmp-dir"
#./gradlew run --args="-e inlineA -o class --doop-dir /home/xinsu/Desktop/Thesis/doop --inline --optimize --keep-tmp-dir"
#./gradlew run --args="-e inlineB -o class --doop-dir /home/xinsu/Desktop/Thesis/doop --inline --optimize --keep-tmp-dir"
#./gradlew run --args="-e inlineC -o class --doop-dir /home/xinsu/Desktop/Thesis/doop --inline --optimize --keep-tmp-dir"
#./gradlew run --args="-e inlineD -o class --doop-dir /home/xinsu/Desktop/Thesis/doop --inline --optimize --keep-tmp-dir"
