// --- Input facts ---
isSerializerMethod("<InlineC: java.lang.String toHexString(java.lang.String)>").
SerializerInputParam("<InlineC: java.lang.String toHexString(java.lang.String)>", 0).
isDeserializerMethod("<InlineC: java.lang.String fromHexString(java.lang.String)>").
DeserializerInputParam("<InlineC: java.lang.String fromHexString(java.lang.String)>", 0).
isInverse("<InlineC: java.lang.String toHexString(java.lang.String)>", "<InlineC: java.lang.String fromHexString(java.lang.String)>").
